### ISSUE TITLE
Can libnotify dependency be made optional?

### ISSUE THREAD

**Issue by vaeth** [deuiore/palemoon-overlay#15]
Is the dependency on libnotify really hard and non-optional for palemoon?
I am surprised, because firefox does not have this dependency.
This dependency is so serious, because it requires installation of gtk+-3; I would like to stay with gtk-2, only (which is sufficient for firefox, and perhaps also for palemoon).

**Comment by Axiomatic-** [comment]
The configure.in does not seem to check whether you have libnotify installed. So Pale Moon does not have a hard dependency for libnotify. Looking at the back end code without it all that happens it notifications are drawn with XUL instead of the [native] system scheme.

Have you tried building Pale Moon without pulling libnotify? It should not error.

**Comment by vaeth** [comment]
It compiled and started without any apparent error

**Comment by deuiore** [comment]
Gone in the Pale Moon 26.0.0 ebuilds.
