### ISSUE TITLE
Pale Moon 27.0.3-r1 - configure: error: cannot determine icu version number from uvernum.h header file

### ISSUE THREAD

**Issue by Nheghathivhistha** [deuiore/palemoon-overlay#31]
Configure fails to find ICU version, version installed is icu-58.2:

0:25.05 sed: character class syntax is [[:space:]], not [:space:]
0:25.05 configure: error: cannot determine icu version number from uvernum.h header file

Should I report this to upstream?

**Comment by Bfgeshka** [comment]
I've got same error, same icu version.

**Comment by Nheghathivhistha** [comment]
Firefox is affected too and it is due to sed-4.3 being more strict. Sed-4.2.2 is fine.
Reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850972

**Comment by deuiore** [comment]
Could you confirm this happening with the palemoon-27.1.0 ebuild too?

**Comment by Bfgeshka** [comment]
didn't try your ebuild, took too long to wait for. Made my own: https://github.com/Bfgeshka/octopus/blob/master/www-client/palemoon/palemoon-27.1.0-r1.ebuild

Compiles fine, sed-4.4. Bug was fixed in palemoon repo itself, no need to create workarounds, more info here: https://github.com/MoonchildProductions/Pale-Moon/issues/836

**Comment by deuiore** [comment]
I guess I can close this then.
