### ISSUE TITLE
Version bump: 27+

### ISSUE THREAD

**Issue by Massimo-B** [deuiore/palemoon-overlay#33]
Hi,
why is palemoon-27+ still masked? Make it at least ~amd64 testing as this is the current stable branch and 26.5 won't even get any support from the community anymore.

For me, as the most important addon finally got branched to support 27+, it's time to move to palemoon 27:
https://forum.palemoon.org/viewtopic.php?f=46&t=13755&start=20#p104589
https://github.com/madand/pentadactyl-pm

**Comment by Massimo-B** [comment]
Just to mention, www-client/palemoon-bin-27.0.3 is running fine here, but I like to build it the gentoo-way.
Can't you make it depend on and use some gcc-4.9 as I have that toolchain also available?

**Comment by deuiore** [comment]
That's the thing: I can't. The only acceptable way is to tell the user to switch their compiler profile every time as it does right now, and you'll agree with me that an ebuild that does that is not production-ready.

Meanwhile I unmasked palemoon-bin since it doesn't have that problem and given the recent developments with PMkit and FFmpeg I think Palemoon 27.1 is more than ready.
