### ISSUE TITLE
palemoon-bin 27.1.* fails to start

### ISSUE THREAD

**Issue by caadar** [deuiore/palemoon-overlay#39]
Older versions works fine, but from 27.1.1 palemoon-bin fails to start.

System: Gentoo
Kernel: 4.7.10-hardened-20170117
Package manager: Paludis
Command: palemoon-bin
Output:

/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: /opt/palemoon/palemoon: no version information available (required by /opt/palemoon/palemoon)
/opt/palemoon/palemoon: relocation error: /opt/palemoon/palemoon: symbol , version  not defined in file  with link time reference

-----

When installs a lot of "Not enough room for program headers, try linking with -N" messages appears.
(see my attached log).
[www-client-palemoon-bin-27.1.2.log.txt](https://github.com/deuiore/palemoon-overlay/files/843716/www-client-palemoon-bin-27.1.2.log.txt)

**Comment by caadar** [comment]
The same for 27.2.0 version.

**Comment by deuiore** [comment]
Does it work when emerged with portage?

Could you please try editing the ebuild and commenting/deleting lines 103 to 106 and see if it works that way?

**Comment by caadar** [comment]
With commented lines 103-106 PM installes and starts at my setup as expected.

**Comment by caadar** [comment]
Work as expected if emerged with Portage.

Well, Paludis is stricter than Portage.

BTW, according to man 5 ebuild:

pkg_preinst pkg_postinst
       All  modifications  required on the live-filesystem before and after the package
       is merged should be placed here.

So please check my patch for the last ebuild.

[palemoon-bin-27.2.0-r1.patch.txt](https://github.com/deuiore/palemoon-overlay/files/867219/palemoon-bin-27.2.0-r1.patch.txt)

**Comment by vaeth** [comment]
> Well, Paludis is stricter than Portage.

Apparently, Paludis is buggy here: It attempts to mess around the binaries with "strip" and perhaps other programs although being explicitly told with RESTRICT="strip" that it must not do so.

> All modifications required on the live-filesystem before and after the package is merged should be placed here.

Neither patchelf nor pax-mark modify the live-filesystem in the original ebuild, and neither should they. Modification of the live-filesystem should be a last resort when this is absolutely necessary (i.e. when a file not belonging to the package has to be created/modified). In particular, a buggy copying ability of a package manager from $D to the live filesystem should be no such reason: This should be fixed in the package manager and not worked around in a dirty way by the ebuild.

**Comment by caadar** [comment]
> Paludis is buggy here

It would be nice if you could open a bug at [paludis.exherbo.org/trac](http://paludis.exherbo.org/trac).

> Neither patchelf nor pax-mark modify the live-filesystem in the original ebuild, and neither should they. 

It shows the direction.

Anyway common practice looks like `patchelf' is used in the main portage tree only before `src_install' phase.

I propose shift it after that phase and make this ebuild useful for Paludis users.

**Comment by vaeth** [comment]
I will not open a paludis bug, because I do not use paludis.

To avoid a misunderstanding: I am not the maintainer of the palemoon ebuild, so my opinion is also just a suggestion.

> common practice looks like patchelf is used in the main portage tree only before src_install phase. I propose shift it after that phase

It is not only common practice, but there are several reasons why it would be wrong to have it after the src_install phase:

1. The checksum stored in /var/db would differ from the actual binary. Thus, tools like qcheck report a modification. This is very inconvenient when one actually wants to verify the installed files e.g. if one suspects a disk/filesystem corruption.
2. The package manager is not made aware about the modifications, thus possibly storing internally wrong dependencies. (I have not checked whether this actually breaks @preserved-rebuild in portage again, but it might very well be so. Also other tools using the package manager's database might become confused by the difference between the files and dependencies stored by the package manager and the differing data on the live system.)

**Comment by caadar** [comment]
It is not Paludis bug, just misconfiguration in my setup. Fixed.

**Comment by caadar** [comment]
Finally culprit found.
In palemoon-bin ebuilds since 27.0.1 there are two RESTRICT lines:

RESTRICT="strip mirror"
and
RESTRICT="mirror"

It seems Portage stops parsing on first item found (RESTRICT="strip mirror") but Paludis builds working environment after all file parsed (and sees RESTRICT="mirror" only).

If second statement commented all works as expected without additional tricky Paludis configuration.

**Comment by deuiore** [comment]
Uh wow, that's been there for a very long time and I have no idea how it happened in the first place and how I never noticed it. Will fix it immediately.
