### ISSUE TITLE
Please support USE=system-cairo separated from USE=system-libs

### ISSUE THREAD

**Issue by vaeth** [deuiore/palemoon-overlay#40]
I had observed a lot of random segfaults with all versions of >=palemoon-27[system-libs], compiled with gcc-6.

After patching the ebuild to use --disable-system-cairo (despite USE=system-libs), no segfault occurred anymore.

Also for firefox it is a well-known problem that system-cairo causes various crashes with various firefox versions, see e.g. Comment 1 in https://bugs.gentoo.org/show_bug.cgi?id=564918. For this reason, I had to disable system-cairo for firefox already since many versions.

It would be nice, if the same disabling could be done with the palemoon ebuild without patching the ebuild (and without being forced to disable all other system libraries).

(Maybe after this separation it is even possible to disable the ban for >=gcc-5 and palemoon-27? At least my gcc-6.3.0 compiled palemoon-27.1.2 runs without any problems…)

**Comment by deuiore** [comment]
I'm actually considering the removal of all of the libraries that have been patched in the Pale Moon source tree from the ones included in system-libs, since using the system libraries instead of them seems to be one of the main sources of problems.

Anyway, I do all my testing with USE=-system-libs and unfortunately that still doesn't solve the random crashes issue for me when compiling with >=gcc-5.

**Comment by deuiore** [comment]
Closing this since cairo is always built-in now.
